#!/usr/bin/env bash
# 2014, s.andres@syseleven.de

set -x

cd /tmp/ &&

# mount metadata drive
mkdir /config
if mount -t iso9660 -o ro /dev/disk/by-label/config-2 /config; then
    grep -q '/dev/disk/by-label/config-2.*/config' /etc/fstab || echo '/dev/disk/by-label/config-2 /config iso9660 defaults 0 0' >> /etc/fstab
fi

# set tz
rm /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime

# Fix /etc/hosts
addr_private=$(ip addr show dev eth0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f 1)
hostname=$(hostname -s)
if ! egrep -q "^${addr_private}" /etc/hosts; then
    echo "${addr_private} ${hostname}.local ${hostname}.openstacklocal ${hostname}" >> /etc/hosts;
fi

cp /home/ubuntu/.ssh/authorized_keys /root/.ssh/authorized_keys
chown root:root /root/.ssh/authorized_keys

# Use Puppetlabs' repository for up-to-date puppet packages
. /etc/lsb-release
wget -c https://apt.puppetlabs.com/puppetlabs-release-${DISTRIB_CODENAME}.deb &&
dpkg -i puppetlabs-release-${DISTRIB_CODENAME}.deb &&

aptitude update

# avahi-daemon needed for local DNS
aptitude install -y \
                    avahi-daemon \
                    bash-completion \
                    build-essential \
                    ethtool \
                    git \
                    jq \
                    ntp \
                    puppet \
                    python-pip \
                    rsync \
                    rubygems \
                    screen \
                    vim \
                    wget \

update-alternatives --set editor /usr/bin/vim.basic
