#!/usr/bin/env bash

set -x


hiera_yaml_location=$(jq -r .meta.hiera_yaml_location /config/openstack/latest/meta_data.json)

if [[ $hiera_yaml_location = "null" ]]; then # jq(1) always returns 0, so we need to parse its output.
  hiera_yaml_location=''
fi


if [[ $hiera_yaml_location ]]; then
    # Disable most cloudstrap features and use static hiera.yaml
    if [[ -f $hiera_yaml_location ]]; then
        # copy static hiera.yaml to proper place
        ln -sf "$hiera_yaml_location" "/etc/puppet/hiera.yaml"

        # Symlink configuration directories for project specific configurations.

        ln -sf ${config_dir}/puppet/hieradata /etc/puppet/hieradata/project-config
        ln -sf ${sys11_config_dir}/puppet/hieradata /etc/puppet/hieradata/sys11-config
    else
        echo "'$hiera_yaml_location' hiera.yaml was not found"
        exit 1
    fi
else
    gen_hieradata
fi

ln -sf /etc/puppet/hiera.yaml /etc/hiera.yaml

cp /opt/override.yaml /etc/puppet/hieradata/override.yaml

programs=(bin/run_puppet_hiera bin/really_run_puppet_agent bin/run_repodeploy bin/facter_to_hiera bin/show_pm_repos bin/hiera_dump bin/run_puppet_apply)
for program in "${programs[@]}"; do
    ln -s ${scripts_dir}/${program} /usr/local/sbin
done

cat > /etc/puppet/manifests/site.pp <<'EOF'
# Gets rid of
#  Warning: The package type's allow_virtual parameter will be changing its default value from false to true in a future release. If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
#   (at /usr/lib/ruby/site_ruby/1.8/puppet/type.rb:816:in `set_default')

Package{
  allow_virtual => true,
}

stage { 'last': }
stage { 'first': }
Stage['first'] -> Stage['main']
Stage['main'] -> Stage['last']

hiera_include('classes')
EOF

run_repodeploy  # Deploy configured repositories (if any)

rm -rf /etc/puppet/modules   # No longer needed now (run_puppet_hiera doesn't include this in its module path.)
