#!/usr/bin/env bash

set -x

# 2014, j.grassler@syseleven.de

# Project specific configuration is optional and may have remained unspecified.

if [ -n "$config_repo" ]; then
  git clone --branch "${config_branch}" "${config_repo}" "${config_dir}"
fi

git clone --branch "${sys11_config_branch}" "${sys11_config_repo}" "${sys11_config_dir}"
git clone --branch "${repodeploy_branch}" "${repodeploy_repo}" /opt/puppet-modules/repodeploy
